// ----------------------------------------------------------------------
// Copyright 2025 Jody Hagins
// Distributed under the MIT Software License
// See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT
// ----------------------------------------------------------------------
#ifndef WJH_SLOTMAP_4E8B9D2A3F7C1E6D9A8B5C4F2E1D3A7B
#define WJH_SLOTMAP_4E8B9D2A3F7C1E6D9A8B5C4F2E1D3A7B

/**
 * Umbrella header for wjh_slotmap library.
 * Includes all public API headers for convenience.
 *
 * Instead of including individual files, you can simply use:
 *   #include <wjh/slotmap.hpp>
 */

#include "wjh/slotmap/Key.hpp"
#include "wjh/slotmap/SlotMap.hpp"

// Version header is generated by CMake. Include only if available.
// For non-CMake builds, version info is not available.
#if __has_include("wjh/slotmap/version.hpp")
    #include "wjh/slotmap/version.hpp"
#endif

#endif // WJH_SLOTMAP_4E8B9D2A3F7C1E6D9A8B5C4F2E1D3A7B
